# Setup
title:            Deprecated

author:
  name:           'Simon Brand'
  url:            https://twitter.com/TartanLlama

github:
  repo:           https://github.com/TartanLlama/cpplang-code-of-conduct
